---
apiVersion: source.toolkit.fluxcd.io/v1beta2
kind: OCIRepository
metadata:
  name: nekia-qiita-oci-podinfo-main
  namespace: flux-system
spec:
  interval: 30s
  provider: generic
  ref:
    tag: latest
  secretRef:
    name: ghcr-secret
  url: oci://ghcr.io/nekia/manifests/podinfo

---
apiVersion: kustomize.toolkit.fluxcd.io/v1beta2
kind: Kustomization
metadata:
  name: oci-podinfo
  namespace: flux-system
spec:
  interval: 30s
  path: ./
  prune: true
  sourceRef:
    kind: OCIRepository
    name: nekia-qiita-oci-podinfo-main
  targetNamespace: flux-system

